# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\module\gui\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(700, 400)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Window)
        self.dateTimeEdit.setGeometry(QtCore.QRect(60, 30, 181, 21))
        self.dateTimeEdit.setObjectName("dateTimeEdit")

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "M&N Stock"))
